### ISSUE TITLE
ReferenceError: Mix is not defined

### ISSUE THREAD

**Issue by adamsir** [ntavelis/webpack-build-notifications#1]
#issue 
ReferenceError: Mix is not defined at `node_modules/webpack-build-notifications/Notifier.js:41`

**Comment by ntavelis** [comment]
Thank you for pointing out this issue, should be fixed in version 0.3.2. Test it and let me know.

**Comment by adamsir** [comment]
It works. Thanks for the solution.

**Comment by ntavelis** [comment]
👍
